In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [2]:
location= 'Data/properatti.csv'

df = pd.read_csv(location, index_col=0)

In [3]:
# Filtro s√≥lo CABA y elmino los stores del tipo de propiedad
df2 = df[(df['property_type'].isin(['apartment','house','PH'])) & (df['state_name'] == 'Capital Federal')]

# Chequeo NaN
display(df2.info())

# Saco las columnas operatcion y estado, ya que son columnas con un solo valor y sin NA (,'rooms')
df2 = df2.drop(['lat-lon','floor','expenses','operation', 'state_name', 'lat','lon','place_with_parent_names', 'country_name', 'geonames_id','price','currency'], axis=1)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30952 entries, 0 to 121219
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   operation                   30952 non-null  object
 1   property_type               30952 non-null  object
 2   place_name                  30952 non-null  object
 3   place_with_parent_names     30952 non-null  object
 4   country_name                30952 non-null  object
 5   state_name                  30952 non-null  object
 6   geonames_id                 29737 non-null  float64
 7   lat-lon                     22631 non-null  object
 8   lat                         22631 non-null  float64
 9   lon                         22631 non-null  float64
 10  price                       27828 non-null  float64
 11  currency                    27828 non-null  object
 12  price_aprox_local_currency  27828 non-null  float64
 13  price_aprox_usd             27828 non-null  float64
 14  surface_total_in_m2         25372 non-null  float64
 15  surface_covered_in_m2       28800 non-null  float64
 16  price_usd_per_m2            22519 non-null  float64
 17  price_per_m2                26276 non-null  float64
 18  floor                       3001 non-null   float64
 19  rooms                       15283 non-null  float64
 20  expenses                    6390 non-null   float64
 21  properati_url               30952 non-null  object
 22  description                 30952 non-null  object
 23  title                       30952 non-null  object
 24  image_thumbnail             30477 non-null  object
dtypes: float64(13), object(12)
memory usage: 6.1+ MB

None

In [4]:
df2['place_name'].value_counts()

Belgrano           2925
Palermo            2773
Caballito          2235
Villa Urquiza      1605
Recoleta           1453
                   ...
Palermo Viejo        36
Villa Real           36
Villa Soldati        13
Villa Riachuelo       6
Catalinas             3
Name: place_name, Length: 62, dtype: int64

In [5]:
df2.columns

Index(['property_type', 'place_name', 'price_aprox_local_currency',
       'price_aprox_usd', 'surface_total_in_m2', 'surface_covered_in_m2',
       'price_usd_per_m2', 'price_per_m2', 'rooms', 'properati_url',
       'description', 'title', 'image_thumbnail'],
      dtype='object')

## Features de "amenities"

In [49]:
def clasificarAmenities(dataset):
    ##esta funcion modifica el dataset de manera que agrega las columnas de amenities
    #inicializo columnas
    dataset['tiene_jardin'] = np.NaN
    dataset['tiene_cochera'] = np.NaN
    dataset['tiene_pileta'] = np.NaN
    dataset['tiene_parrilla'] = np.NaN
    
    ##regex
    #Expresiones regulares a utilizar
    re_jardin = re.compile("(jardin|garden|green|parque|parquizado|pasto)+|\s(sum)+", flags=re.IGNORECASE)
    re_cochera = re.compile("(garage|cochera)+|\s(sum)+", flags=re.IGNORECASE)
    re_pileta = re.compile("(pileta|piscina|pile)+|\s(sum)+", flags=re.IGNORECASE)
    re_parrilla = re.compile("(parrilla|bbq|barbaque|asado|asador)+|\s(sum)+", flags=re.IGNORECASE)
    
    #
    for i in dataset.description.index:
        
        dataset.tiene_jardin[i] = 0
        dataset.tiene_cochera[i] = 0
        dataset.tiene_pileta[i] = 0
        dataset.tiene_parrilla[i] = 0
        
        if dataset['description'][i] is not None:
            
            reg_search = re_jardin.search(str(dataset['description'][i]))
            if reg_search:
                dataset.tiene_jardin[i] = 1
                
            reg_search = re_cochera.search(str(dataset['description'][i]))
            if reg_search:
                dataset.tiene_cochera[i] = 1
                
            reg_search = re_pileta.search(str(dataset['description'][i]))
            if reg_search:
                dataset.tiene_pileta[i] = 1
                
            reg_search = re_parrilla.search(str(dataset['description'][i]))
            if reg_search:
                dataset.tiene_parrilla[i] = 1
                
                
        if dataset['title'][i] is not None:
            
            reg_search = re_jardin.search(str(dataset['title'][i]))
            if reg_search:
                dataset.tiene_jardin[i] = 1
                
            reg_search = re_cochera.search(str(dataset['title'][i]))
            if reg_search:
                dataset.tiene_cochera[i] = 1
                
            reg_search = re_pileta.search(str(dataset['title'][i]))
            if reg_search:
                dataset.tiene_pileta[i] = 1
                
            reg_search = re_parrilla.search(str(dataset['title'][i]))
            if reg_search:
                dataset.tiene_parrilla[i] = 1                
                
                              
        if dataset['properati_url'][i] is not None:
            
            reg_search = re_jardin.search(str(dataset['properati_url'][i]))
            if reg_search:
                dataset.tiene_jardin[i] = 1
                
            reg_search = re_cochera.search(str(dataset['properati_url'][i]))
            if reg_search:
                dataset.tiene_cochera[i] = 1
                
            reg_search = re_pileta.search(str(dataset['properati_url'][i]))
            if reg_search:
                dataset.tiene_pileta[i] = 1
                
            reg_search = re_parrilla.search(str(dataset['properati_url'][i]))
            if reg_search:
                dataset.tiene_parrilla[i] = 1                
                  
    return dataset

In [7]:
clasificarAmenities(df2)

C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,property_type,place_name,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,rooms,properati_url,description,title,image_thumbnail,tiene_jardin,tiene_cochera,tiene_pileta,tiene_parrilla
0,PH,Mataderos,1093959.00,62000.0,55.0,40.0,1127.272727,1550.000000,NaN,http://www.properati.com.ar/15bo8_venta_ph_mat...,"2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO,...",2 AMB TIPO CASA SIN EXPENSAS EN PB,https://thumbs4.properati.com/8/BluUYiHJLhgIIK...,0.0,0.0,0.0,0.0
2,apartment,Mataderos,1270404.00,72000.0,55.0,55.0,1309.090909,1309.090909,NaN,http://www.properati.com.ar/15bod_venta_depart...,2 AMBIENTES 3ER PISO LATERAL LIVING COMEDOR AM...,2 AMB 3ER PISO CON ASCENSOR APTO CREDITO,https://thumbs4.properati.com/5/SXKr34F_IwG3W_...,0.0,0.0,0.0,0.0
3,PH,Liniers,1676227.50,95000.0,NaN,NaN,NaN,NaN,NaN,http://www.properati.com.ar/15boh_venta_ph_lin...,PH 3 ambientes con patio. Hay 3 deptos en lote...,PH 3 amb. cfte. reciclado,https://thumbs4.properati.com/3/DgIfX-85Mog5SP...,0.0,0.0,0.0,0.0
7,apartment,Belgrano,2434941.00,138000.0,45.0,40.0,3066.666667,3450.000000,NaN,http://www.properati.com.ar/15bot_venta_depart...,EXCELENTE MONOAMBIENTE A ESTRENAR AMPLIO SUPER...,JOSE HERNANDEZ 1400 MONOAMBIENTE ESTRENAR CAT...,https://thumbs4.properati.com/1/IHxARynlr8sPEW...,0.0,0.0,1.0,0.0
8,apartment,Belgrano,3440677.50,195000.0,65.0,60.0,3000.000000,3250.000000,NaN,http://www.properati.com.ar/15bou_venta_depart...,EXCELENTE DOS AMBIENTES ESTRENAR AMPLIO SUPER...,"JOSE HERNANDEZ 1400 DOS AMBIENTES ESTRENAR ,...",https://thumbs4.properati.com/2/J3zOjgaFHrkvnv...,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121160,apartment,Belgrano,7234245.00,410000.0,157.0,NaN,2611.464968,NaN,NaN,http://www.properati.com.ar/1cj5v_venta_depart...,Edificio en esquina de muy buena categor√≠a de ...,Av .Luis Maria Campos 1400- Belgrano-Capital F...,https://thumbs4.properati.com/0/zeLNBuyylOJL7z...,1.0,0.0,0.0,0.0
121209,apartment,Belgrano,7234245.00,410000.0,157.0,NaN,2611.464968,NaN,NaN,http://www.properati.com.ar/1cj7c_venta_depart...,Edificio en esquina de muy buena categor√≠a de ...,Av .Luis Maria Campos 1400- Belgrano-Capital F...,https://thumbs4.properati.com/0/zeLNBuyylOJL7z...,1.0,0.0,0.0,0.0
121215,apartment,Belgrano,15350715.00,870000.0,113.0,93.0,7699.115044,9354.838710,NaN,http://www.properati.com.ar/1cja2_venta_depart...,TORRE FORUM ALCORTA - M√ÅXIMA CATEGOR√çA.Impecab...,Torre Forum Alcorta- Impecable 3 ambientes,https://thumbs4.properati.com/1/bjms0KnaAnlNoQ...,0.0,1.0,1.0,1.0
121217,apartment,Villa Urquiza,2320251.75,131500.0,46.0,39.0,2858.695652,3371.794872,NaN,http://www.properati.com.ar/1cja7_venta_depart...,VENTA DEPARTAMENTO AMBIENTE DIVISIBLE A ESTREN...,VENTA DEPARTAMENTO AMBIENTE DIVISIBLE A ESTREN...,https://thumbs4.properati.com/9/YAe_-2gRVykADP...,0.0,1.0,0.0,1.0
121219,apartment,Capital Federal,2276140.50,129000.0,77.0,77.0,1675.324675,1675.324675,NaN,http://www.properati.com.ar/1cjaa_venta_depart...,Departamento de 77 m2 apto profesional. Edific...,Departamento apto profesional en el Centro,https://thumbs4.properati.com/8/mNEsnQWqB7joBF...,0.0,0.0,0.0,0.0

## Columnas a agregar/eliminar

- Amenities: Booleano. Pileta, garage/cochera, parrilla, sum, garden/jardin
- Cuota: Booleano. Ver si sigue aplicando para planes, y si eliminamos o no.
- superficie: unificar los regex de los dos grupos
- Sup total y cubierta: Tomas buscar√° en los trabajos del resto. Julio hab√≠a imputado esto, traer el c√≥digo al nuevo dataset. Revisar le tema de las que tiene valores diferentes.
- image_thumbnail: Ver si los duplicados que se encontraron son relevantes en el nuevo dataset, y ulego eliminarla
- Floor: Aplicar el regex y ver con cuantos datos nos quedamos.
- rooms y ambientes: Ver los regex que se armaron, como aplican al nuevo dataset
- expensas por ahora se elimina
- Description y title: Se saca todos los datos y se elimina

## Agregado de columnas "ambientes", "cuota"e imputaci√≥n de superficie

In [8]:
def superficie(df2):

    #regex para encontrar las diferentes caracter√≠sticas

    patron = '(?P<m2>\d\d\d+\s\s*m2|\d\d\d+\s\s*M2|\d\d\d+\s\s*metro|\d\d\d+\s\s*METRO)|(?P<ambiente>\d+\sambiente|\d+\sAMBIENTE|\d+\sAMB|\d+\samb|\d+\sAMBS|\d+\sambs)|(?P<balcon>balcon|BALCON)|(?P<planta_alta>planta\salta|PLANTA\sALTA)|(?P<patio>patio|PATIO)|(?P<duplex>duplex|DUPLEX)|(?P<cuota>cuota|CUOTA)|(?P<amenities>parrilla|bbq|barbaque|asado|asador|cochera|pileta|piscina|pile|patio|terraza|solarium|pile|jardin|garden|green|parque|parquizado|pasto)+|\s(sum)+'
    patron_regex = re.compile(patron)
    patron_match = df2.description.apply(lambda x : patron_regex.search(str(x)))

    # Extrae los metros cuadrados de la descripci√≥n, luego extrae el n√∫mero (sin unidad) y posteriormente elimina aquellos menores que 3 para que no tome por error el n√∫mero 2 de la unidad de medida
    # Genera una serie m2

    m2 = patron_match.apply(lambda x: x if x is None else x.group('m2'))
    patron_num = '\d+'
    patron_num_regex = re.compile(patron_num)
    m2 = m2.apply(lambda x: x if x is None else patron_num_regex.findall(x))
    # Extrae solo el valor de la superficie, evitando considerar el 2 de "m2"
    m2 = m2.apply(lambda x: x if x is None else x[0])
    m2 = pd.to_numeric(m2)
    m2 = m2.apply(lambda x: x if x is None else (None if x<3 else x))

    # Extrae la cantidad de ambientes, de la descripci√≥n, luego extrae el n√∫mero (sin unidad) y posteriormente elimina aquellos menores que 3 para que no tome por error el n√∫mero 2 de la unidad de medida
    # Genera una serie ambientes

    ambientes = patron_match.apply(lambda x: x if x is None else x.group('ambiente'))
    ambientes = ambientes.apply(lambda x: x if x is None else x[0])
    ambientes = pd.to_numeric(ambientes)


    # Extrae la cantidad de ambientes, balc√≥n, patio, duplex, y planta alta y amenities de la descripci√≥n. Genera una serie booleana

    #balcon = patron_match.apply(lambda x: x if x is None else x.group('balcon'))
    #balcon = balcon.apply(lambda x: False if x is None else True)

    #patio = patron_match.apply(lambda x: x if x is None else x.group('patio'))
    #patio = patio.apply(lambda x: False if x is None else True)

    #duplex = patron_match.apply(lambda x: x if x is None else x.group('duplex'))
    #duplex = duplex.apply(lambda x: False if x is None else True)

    #planta_alta = patron_match.apply(lambda x: x if x is None else x.group('planta_alta'))
    #planta_alta = planta_alta.apply(lambda x: False if x is None else True)

    #amenities = patron_match.apply(lambda x: x if x is None else x.group('amenities'))
    #amenities = amenities.apply(lambda x: False if x is None else True)

    cuota = patron_match.apply(lambda x: x if x is None else x.group('cuota'))
    cuota = cuota.apply(lambda x: 0 if x is None else 1)
    
    df2['sup_m2_re'] = m2
    df2['ambientes'] = ambientes
    df2['cuota'] = cuota
    
    return df2

In [9]:
superficie(df2)

,property_type,place_name,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,rooms,properati_url,description,title,image_thumbnail,tiene_jardin,tiene_cochera,tiene_pileta,tiene_parrilla,sup_m2_re,ambientes,cuota
0,PH,Mataderos,1093959.00,62000.0,55.0,40.0,1127.272727,1550.000000,NaN,http://www.properati.com.ar/15bo8_venta_ph_mat...,"2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO,...",2 AMB TIPO CASA SIN EXPENSAS EN PB,https://thumbs4.properati.com/8/BluUYiHJLhgIIK...,0.0,0.0,0.0,0.0,NaN,2.0,0
2,apartment,Mataderos,1270404.00,72000.0,55.0,55.0,1309.090909,1309.090909,NaN,http://www.properati.com.ar/15bod_venta_depart...,2 AMBIENTES 3ER PISO LATERAL LIVING COMEDOR AM...,2 AMB 3ER PISO CON ASCENSOR APTO CREDITO,https://thumbs4.properati.com/5/SXKr34F_IwG3W_...,0.0,0.0,0.0,0.0,NaN,2.0,0
3,PH,Liniers,1676227.50,95000.0,NaN,NaN,NaN,NaN,NaN,http://www.properati.com.ar/15boh_venta_ph_lin...,PH 3 ambientes con patio. Hay 3 deptos en lote...,PH 3 amb. cfte. reciclado,https://thumbs4.properati.com/3/DgIfX-85Mog5SP...,0.0,0.0,0.0,0.0,NaN,3.0,0
7,apartment,Belgrano,2434941.00,138000.0,45.0,40.0,3066.666667,3450.000000,NaN,http://www.properati.com.ar/15bot_venta_depart...,EXCELENTE MONOAMBIENTE A ESTRENAR AMPLIO SUPER...,JOSE HERNANDEZ 1400 MONOAMBIENTE ESTRENAR CAT...,https://thumbs4.properati.com/1/IHxARynlr8sPEW...,0.0,0.0,1.0,0.0,NaN,NaN,0
8,apartment,Belgrano,3440677.50,195000.0,65.0,60.0,3000.000000,3250.000000,NaN,http://www.properati.com.ar/15bou_venta_depart...,EXCELENTE DOS AMBIENTES ESTRENAR AMPLIO SUPER...,"JOSE HERNANDEZ 1400 DOS AMBIENTES ESTRENAR ,...",https://thumbs4.properati.com/2/J3zOjgaFHrkvnv...,0.0,0.0,1.0,0.0,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121160,apartment,Belgrano,7234245.00,410000.0,157.0,NaN,2611.464968,NaN,NaN,http://www.properati.com.ar/1cj5v_venta_depart...,Edificio en esquina de muy buena categor√≠a de ...,Av .Luis Maria Campos 1400- Belgrano-Capital F...,https://thumbs4.properati.com/0/zeLNBuyylOJL7z...,1.0,0.0,0.0,0.0,NaN,NaN,0
121209,apartment,Belgrano,7234245.00,410000.0,157.0,NaN,2611.464968,NaN,NaN,http://www.properati.com.ar/1cj7c_venta_depart...,Edificio en esquina de muy buena categor√≠a de ...,Av .Luis Maria Campos 1400- Belgrano-Capital F...,https://thumbs4.properati.com/0/zeLNBuyylOJL7z...,1.0,0.0,0.0,0.0,NaN,NaN,0
121215,apartment,Belgrano,15350715.00,870000.0,113.0,93.0,7699.115044,9354.838710,NaN,http://www.properati.com.ar/1cja2_venta_depart...,TORRE FORUM ALCORTA - M√ÅXIMA CATEGOR√çA.Impecab...,Torre Forum Alcorta- Impecable 3 ambientes,https://thumbs4.properati.com/1/bjms0KnaAnlNoQ...,0.0,1.0,1.0,1.0,NaN,NaN,0
121217,apartment,Villa Urquiza,2320251.75,131500.0,46.0,39.0,2858.695652,3371.794872,NaN,http://www.properati.com.ar/1cja7_venta_depart...,VENTA DEPARTAMENTO AMBIENTE DIVISIBLE A ESTREN...,VENTA DEPARTAMENTO AMBIENTE DIVISIBLE A ESTREN...,https://thumbs4.properati.com/9/YAe_-2gRVykADP...,0.0,1.0,0.0,1.0,NaN,NaN,0
121219,apartment,Capital Federal,2276140.50,129000.0,77.0,77.0,1675.324675,1675.324675,NaN,http://www.properati.com.ar/1cjaa_venta_depart...,Departamento de 77 m2 apto profesional. Edific...,Departamento apto profesional en el Centro,https://thumbs4.properati.com/8/mNEsnQWqB7joBF...,0.0,0.0,0.0,0.0,NaN,NaN,0

In [10]:
#Unificaci√≥n rooms y ambientes
def unif_rooms_amb(data):
    for i in data.index:
        if pd.isna(data.loc[i, 'rooms']) & pd.notna(data.loc[i, 'ambientes']):
            data.loc[i, 'rooms'] = data.loc[i, 'ambientes']
    
    return data

In [11]:
unif_rooms_amb(df2)

,property_type,place_name,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,rooms,properati_url,description,title,image_thumbnail,tiene_jardin,tiene_cochera,tiene_pileta,tiene_parrilla,sup_m2_re,ambientes,cuota
0,PH,Mataderos,1093959.00,62000.0,55.0,40.0,1127.272727,1550.000000,2.0,http://www.properati.com.ar/15bo8_venta_ph_mat...,"2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO,...",2 AMB TIPO CASA SIN EXPENSAS EN PB,https://thumbs4.properati.com/8/BluUYiHJLhgIIK...,0.0,0.0,0.0,0.0,NaN,2.0,0
2,apartment,Mataderos,1270404.00,72000.0,55.0,55.0,1309.090909,1309.090909,2.0,http://www.properati.com.ar/15bod_venta_depart...,2 AMBIENTES 3ER PISO LATERAL LIVING COMEDOR AM...,2 AMB 3ER PISO CON ASCENSOR APTO CREDITO,https://thumbs4.properati.com/5/SXKr34F_IwG3W_...,0.0,0.0,0.0,0.0,NaN,2.0,0
3,PH,Liniers,1676227.50,95000.0,NaN,NaN,NaN,NaN,3.0,http://www.properati.com.ar/15boh_venta_ph_lin...,PH 3 ambientes con patio. Hay 3 deptos en lote...,PH 3 amb. cfte. reciclado,https://thumbs4.properati.com/3/DgIfX-85Mog5SP...,0.0,0.0,0.0,0.0,NaN,3.0,0
7,apartment,Belgrano,2434941.00,138000.0,45.0,40.0,3066.666667,3450.000000,NaN,http://www.properati.com.ar/15bot_venta_depart...,EXCELENTE MONOAMBIENTE A ESTRENAR AMPLIO SUPER...,JOSE HERNANDEZ 1400 MONOAMBIENTE ESTRENAR CAT...,https://thumbs4.properati.com/1/IHxARynlr8sPEW...,0.0,0.0,1.0,0.0,NaN,NaN,0
8,apartment,Belgrano,3440677.50,195000.0,65.0,60.0,3000.000000,3250.000000,NaN,http://www.properati.com.ar/15bou_venta_depart...,EXCELENTE DOS AMBIENTES ESTRENAR AMPLIO SUPER...,"JOSE HERNANDEZ 1400 DOS AMBIENTES ESTRENAR ,...",https://thumbs4.properati.com/2/J3zOjgaFHrkvnv...,0.0,0.0,1.0,0.0,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121160,apartment,Belgrano,7234245.00,410000.0,157.0,NaN,2611.464968,NaN,NaN,http://www.properati.com.ar/1cj5v_venta_depart...,Edificio en esquina de muy buena categor√≠a de ...,Av .Luis Maria Campos 1400- Belgrano-Capital F...,https://thumbs4.properati.com/0/zeLNBuyylOJL7z...,1.0,0.0,0.0,0.0,NaN,NaN,0
121209,apartment,Belgrano,7234245.00,410000.0,157.0,NaN,2611.464968,NaN,NaN,http://www.properati.com.ar/1cj7c_venta_depart...,Edificio en esquina de muy buena categor√≠a de ...,Av .Luis Maria Campos 1400- Belgrano-Capital F...,https://thumbs4.properati.com/0/zeLNBuyylOJL7z...,1.0,0.0,0.0,0.0,NaN,NaN,0
121215,apartment,Belgrano,15350715.00,870000.0,113.0,93.0,7699.115044,9354.838710,NaN,http://www.properati.com.ar/1cja2_venta_depart...,TORRE FORUM ALCORTA - M√ÅXIMA CATEGOR√çA.Impecab...,Torre Forum Alcorta- Impecable 3 ambientes,https://thumbs4.properati.com/1/bjms0KnaAnlNoQ...,0.0,1.0,1.0,1.0,NaN,NaN,0
121217,apartment,Villa Urquiza,2320251.75,131500.0,46.0,39.0,2858.695652,3371.794872,NaN,http://www.properati.com.ar/1cja7_venta_depart...,VENTA DEPARTAMENTO AMBIENTE DIVISIBLE A ESTREN...,VENTA DEPARTAMENTO AMBIENTE DIVISIBLE A ESTREN...,https://thumbs4.properati.com/9/YAe_-2gRVykADP...,0.0,1.0,0.0,1.0,NaN,NaN,0
121219,apartment,Capital Federal,2276140.50,129000.0,77.0,77.0,1675.324675,1675.324675,NaN,http://www.properati.com.ar/1cjaa_venta_depart...,Departamento de 77 m2 apto profesional. Edific...,Departamento apto profesional en el Centro,https://thumbs4.properati.com/8/mNEsnQWqB7joBF...,0.0,0.0,0.0,0.0,NaN,NaN,0

In [12]:
mask_sup_cov = (df2['sup_m2_re'].notna()) & (df2['surface_covered_in_m2'].isna())
mask_sup_cov.sum()

82

In [13]:
# Funci√≥n que completa datos faltantes de superficie con datos extra√≠dos de la descripci√≥n.
def compl_m2_re (row):
    if row['surface_covered_in_m2']>=0:
        result = row['surface_covered_in_m2']
    else:
        result = row['sup_m2_re']
    return result

df2['surface_covered_in_m2'] = df2.apply(compl_m2_re, axis = 1)

In [14]:
# Verifico si se imputaron correctamente.

df2['surface_covered_in_m2'].notnull().sum()

28882

In [15]:
# Determinar la cantidad de filas que pueden tener invertidas los datos de superficie cubierta con superficie total

sup_mask = df2['surface_covered_in_m2'] > df2['surface_total_in_m2']
print(f'Cantidad de filas con sup_cov > sup_total {sup_mask.sum()}')

Cantidad de filas con sup_cov > sup_total 131

In [16]:
# Funci√≥n para corregir los valores invertidos de superficie cubierta y superficie total

df2['surface_covered_in_m2_aux'] = df2['surface_covered_in_m2']

def invertir_sup_cov (row):
    if (row['surface_covered_in_m2'] > row['surface_total_in_m2']):
        return row['surface_total_in_m2']
    else:
        return row['surface_covered_in_m2']

def invertir_sup_tot (row):
    if (row['surface_covered_in_m2'] == row['surface_total_in_m2']):
        return row['surface_covered_in_m2_aux']
    else:
        return row['surface_total_in_m2'] 
    
df2.loc[sup_mask,'surface_covered_in_m2'] = df2.apply(invertir_sup_tot, axis=1)
df2.loc[sup_mask,'surface_total_in_m2']  = df2.apply(invertir_sup_tot, axis=1)

In [17]:
df2.columns

Index(['property_type', 'place_name', 'price_aprox_local_currency',
       'price_aprox_usd', 'surface_total_in_m2', 'surface_covered_in_m2',
       'price_usd_per_m2', 'price_per_m2', 'rooms', 'properati_url',
       'description', 'title', 'image_thumbnail', 'tiene_jardin',
       'tiene_cochera', 'tiene_pileta', 'tiene_parrilla', 'sup_m2_re',
       'ambientes', 'cuota', 'surface_covered_in_m2_aux'],
      dtype='object')

In [18]:
# Imputo los valores de superficie cubierta y total, considerando que si tengo uno solo de los dos, son el mismo valor

# Imputo superficie total con los datos de cuubierta
mask_sup_cov = (df2['surface_covered_in_m2'].notna()) & (df2['surface_total_in_m2'].isna())
print('Datos a imputar en sup_total: ',mask_sup_cov.sum())

def compl_m2_cub (row):
    if row['surface_total_in_m2']>=0:
        result = row['surface_total_in_m2']
    else:
        result = row['surface_covered_in_m2']
    return result

df2['surface_total_in_m2'] = df2.apply(compl_m2_cub, axis = 1)
display(df2.info())

# Imputo superficie cubierta con los datos de total
mask_sup_cov = (df2['surface_total_in_m2'].notna()) & (df2['surface_covered_in_m2'].isna())
print('Datos a imputar en sup_cubierta: ',mask_sup_cov.sum())

def compl_m2_tot (row):
    if row['surface_covered_in_m2']>=0:
        result = row['surface_covered_in_m2']
    else:
        result = row['surface_total_in_m2']
    return result

df2['surface_covered_in_m2'] = df2.apply(compl_m2_tot, axis = 1)
display(df2.info())

Datos a imputar en sup_total:  4887
<class 'pandas.core.frame.DataFrame'>
Int64Index: 30952 entries, 0 to 121219
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_type               30952 non-null  object
 1   place_name                  30952 non-null  object
 2   price_aprox_local_currency  27828 non-null  float64
 3   price_aprox_usd             27828 non-null  float64
 4   surface_total_in_m2         30259 non-null  float64
 5   surface_covered_in_m2       28882 non-null  float64
 6   price_usd_per_m2            22519 non-null  float64
 7   price_per_m2                26276 non-null  float64
 8   rooms                       21652 non-null  float64
 9   properati_url               30952 non-null  object
 10  description                 30952 non-null  object
 11  title                       30952 non-null  object
 12  image_thumbnail             30477 non-null  object
 13  tiene_jardin                30952 non-null  float64
 14  tiene_cochera               30952 non-null  float64
 15  tiene_pileta                30952 non-null  float64
 16  tiene_parrilla              30952 non-null  float64
 17  sup_m2_re                   1110 non-null   float64
 18  ambientes                   13027 non-null  float64
 19  cuota                       30952 non-null  int64
 20  surface_covered_in_m2_aux   28882 non-null  float64
dtypes: float64(14), int64(1), object(6)
memory usage: 6.2+ MB

None

Datos a imputar en sup_cubierta:  1377
<class 'pandas.core.frame.DataFrame'>
Int64Index: 30952 entries, 0 to 121219
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_type               30952 non-null  object
 1   place_name                  30952 non-null  object
 2   price_aprox_local_currency  27828 non-null  float64
 3   price_aprox_usd             27828 non-null  float64
 4   surface_total_in_m2         30259 non-null  float64
 5   surface_covered_in_m2       30259 non-null  float64
 6   price_usd_per_m2            22519 non-null  float64
 7   price_per_m2                26276 non-null  float64
 8   rooms                       21652 non-null  float64
 9   properati_url               30952 non-null  object
 10  description                 30952 non-null  object
 11  title                       30952 non-null  object
 12  image_thumbnail             30477 non-null  object
 13  tiene_jardin                30952 non-null  float64
 14  tiene_cochera               30952 non-null  float64
 15  tiene_pileta                30952 non-null  float64
 16  tiene_parrilla              30952 non-null  float64
 17  sup_m2_re                   1110 non-null   float64
 18  ambientes                   13027 non-null  float64
 19  cuota                       30952 non-null  int64
 20  surface_covered_in_m2_aux   28882 non-null  float64
dtypes: float64(14), int64(1), object(6)
memory usage: 6.2+ MB

None

In [19]:
# Elimino la columna auxiliar generada

df2.drop('surface_covered_in_m2_aux', axis=1, inplace=True)
df2.drop('sup_m2_re', axis=1, inplace=True)
#df2.drop('ambientes', axis=1, inplace=True)

In [20]:
# Verificaci√≥n de la correcci√≥n de cambio de columnas e imputaci√≥n.

sup_mask = df2['surface_covered_in_m2'] > df2['surface_total_in_m2']
print(f'Cantidad de filas con sup_cov > sup_total {sup_mask.sum()}')
display(df2.info())

Cantidad de filas con sup_cov > sup_total 0
<class 'pandas.core.frame.DataFrame'>
Int64Index: 30952 entries, 0 to 121219
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_type               30952 non-null  object
 1   place_name                  30952 non-null  object
 2   price_aprox_local_currency  27828 non-null  float64
 3   price_aprox_usd             27828 non-null  float64
 4   surface_total_in_m2         30259 non-null  float64
 5   surface_covered_in_m2       30259 non-null  float64
 6   price_usd_per_m2            22519 non-null  float64
 7   price_per_m2                26276 non-null  float64
 8   rooms                       21652 non-null  float64
 9   properati_url               30952 non-null  object
 10  description                 30952 non-null  object
 11  title                       30952 non-null  object
 12  image_thumbnail             30477 non-null  object
 13  tiene_jardin                30952 non-null  float64
 14  tiene_cochera               30952 non-null  float64
 15  tiene_pileta                30952 non-null  float64
 16  tiene_parrilla              30952 non-null  float64
 17  ambientes                   13027 non-null  float64
 18  cuota                       30952 non-null  int64
dtypes: float64(12), int64(1), object(6)
memory usage: 5.7+ MB

None

##

In [21]:
# sns.jointplot(x='surface_covered_in_m2', y='surface_total_in_m2',data=df2, hue='property_type',xlim=(0,500), ylim=(0,500))

In [22]:
display(df2.columns)
df2.head()

Index(['property_type', 'place_name', 'price_aprox_local_currency',
       'price_aprox_usd', 'surface_total_in_m2', 'surface_covered_in_m2',
       'price_usd_per_m2', 'price_per_m2', 'rooms', 'properati_url',
       'description', 'title', 'image_thumbnail', 'tiene_jardin',
       'tiene_cochera', 'tiene_pileta', 'tiene_parrilla', 'ambientes',
       'cuota'],
      dtype='object')

,property_type,place_name,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,rooms,properati_url,description,title,image_thumbnail,tiene_jardin,tiene_cochera,tiene_pileta,tiene_parrilla,ambientes,cuota
0,PH,Mataderos,1093959.0,62000.0,55.0,40.0,1127.272727,1550.000000,2.0,http://www.properati.com.ar/15bo8_venta_ph_mat...,"2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO,...",2 AMB TIPO CASA SIN EXPENSAS EN PB,https://thumbs4.properati.com/8/BluUYiHJLhgIIK...,0.0,0.0,0.0,0.0,2.0,0
2,apartment,Mataderos,1270404.0,72000.0,55.0,55.0,1309.090909,1309.090909,2.0,http://www.properati.com.ar/15bod_venta_depart...,2 AMBIENTES 3ER PISO LATERAL LIVING COMEDOR AM...,2 AMB 3ER PISO CON ASCENSOR APTO CREDITO,https://thumbs4.properati.com/5/SXKr34F_IwG3W_...,0.0,0.0,0.0,0.0,2.0,0
3,PH,Liniers,1676227.5,95000.0,NaN,NaN,NaN,NaN,3.0,http://www.properati.com.ar/15boh_venta_ph_lin...,PH 3 ambientes con patio. Hay 3 deptos en lote...,PH 3 amb. cfte. reciclado,https://thumbs4.properati.com/3/DgIfX-85Mog5SP...,0.0,0.0,0.0,0.0,3.0,0
7,apartment,Belgrano,2434941.0,138000.0,45.0,40.0,3066.666667,3450.000000,NaN,http://www.properati.com.ar/15bot_venta_depart...,EXCELENTE MONOAMBIENTE A ESTRENAR AMPLIO SUPER...,JOSE HERNANDEZ 1400 MONOAMBIENTE ESTRENAR CAT...,https://thumbs4.properati.com/1/IHxARynlr8sPEW...,0.0,0.0,1.0,0.0,NaN,0
8,apartment,Belgrano,3440677.5,195000.0,65.0,60.0,3000.000000,3250.000000,NaN,http://www.properati.com.ar/15bou_venta_depart...,EXCELENTE DOS AMBIENTES ESTRENAR AMPLIO SUPER...,"JOSE HERNANDEZ 1400 DOS AMBIENTES ESTRENAR ,...",https://thumbs4.properati.com/2/J3zOjgaFHrkvnv...,0.0,0.0,1.0,0.0,NaN,0

In [23]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30952 entries, 0 to 121219
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_type               30952 non-null  object
 1   place_name                  30952 non-null  object
 2   price_aprox_local_currency  27828 non-null  float64
 3   price_aprox_usd             27828 non-null  float64
 4   surface_total_in_m2         30259 non-null  float64
 5   surface_covered_in_m2       30259 non-null  float64
 6   price_usd_per_m2            22519 non-null  float64
 7   price_per_m2                26276 non-null  float64
 8   rooms                       21652 non-null  float64
 9   properati_url               30952 non-null  object
 10  description                 30952 non-null  object
 11  title                       30952 non-null  object
 12  image_thumbnail             30477 non-null  object
 13  tiene_jardin                30952 non-null  float64
 14  tiene_cochera               30952 non-null  float64
 15  tiene_pileta                30952 non-null  float64
 16  tiene_parrilla              30952 non-null  float64
 17  ambientes                   13027 non-null  float64
 18  cuota                       30952 non-null  int64
dtypes: float64(12), int64(1), object(6)
memory usage: 5.7+ MB

## Conversion de pasos a dolares

Tipo de cambio promedio entre entre 'price_aprox_local_currency' y 'price_aprox_usd':  17.64 $/USD

In [24]:
def estimar_tipo_de_cambio(data):
    #'Esta funci√≥n estima el tipo de cambio promedio entre 'price_aprox_local_currency' y 'price_aprox_usd'
    mask_tipo_de_cambio = (data['price_aprox_local_currency'].notnull() & data['price_aprox_usd'].notnull())
    calculo_tipo_de_cambio = data.loc[mask_tipo_de_cambio, 'price_aprox_local_currency'] / data.loc[mask_tipo_de_cambio, 'price_aprox_usd']
    tipo_de_cambio = calculo_tipo_de_cambio.mean()
    valor = round(tipo_de_cambio, 2)
    return valor

In [25]:
valor_dolar = estimar_tipo_de_cambio(df2)
print(valor_dolar)

17.64

In [26]:
def calculo_valor_total_pesos_dolar(dataframe, valor_dolar):
    #precio m2 en pesos a precio m2 en dolares
    for i in dataframe.index:
        if pd.isna(dataframe.loc[i, 'price_usd_per_m2']):
            dataframe.loc[i, 'price_usd_per_m2'] = dataframe.loc[i, 'price_per_m2'] / valor_dolar
    
    return dataframe

In [27]:
df2 = calculo_valor_total_pesos_dolar(df2, valor_dolar)

In [28]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30952 entries, 0 to 121219
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_type               30952 non-null  object
 1   place_name                  30952 non-null  object
 2   price_aprox_local_currency  27828 non-null  float64
 3   price_aprox_usd             27828 non-null  float64
 4   surface_total_in_m2         30259 non-null  float64
 5   surface_covered_in_m2       30259 non-null  float64
 6   price_usd_per_m2            27307 non-null  float64
 7   price_per_m2                26276 non-null  float64
 8   rooms                       21652 non-null  float64
 9   properati_url               30952 non-null  object
 10  description                 30952 non-null  object
 11  title                       30952 non-null  object
 12  image_thumbnail             30477 non-null  object
 13  tiene_jardin                30952 non-null  float64
 14  tiene_cochera               30952 non-null  float64
 15  tiene_pileta                30952 non-null  float64
 16  tiene_parrilla              30952 non-null  float64
 17  ambientes                   13027 non-null  float64
 18  cuota                       30952 non-null  int64
dtypes: float64(12), int64(1), object(6)
memory usage: 5.7+ MB

In [29]:
#Dropeo todas las features que necesitan tratamiento previo para servir
df2 = df2.drop(['description','title','image_thumbnail','price_per_m2','properati_url', 'price_aprox_local_currency'], axis=1)

In [30]:
df2 = df2.drop('ambientes',axis=1)

In [31]:
df2 = df2.dropna()

In [32]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20003 entries, 0 to 121138
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   property_type          20003 non-null  object
 1   place_name             20003 non-null  object
 2   price_aprox_usd        20003 non-null  float64
 3   surface_total_in_m2    20003 non-null  float64
 4   surface_covered_in_m2  20003 non-null  float64
 5   price_usd_per_m2       20003 non-null  float64
 6   rooms                  20003 non-null  float64
 7   tiene_jardin           20003 non-null  float64
 8   tiene_cochera          20003 non-null  float64
 9   tiene_pileta           20003 non-null  float64
 10  tiene_parrilla         20003 non-null  float64
 11  cuota                  20003 non-null  int64
dtypes: float64(9), int64(1), object(2)
memory usage: 2.0+ MB

## test modelado b√°sico

In [33]:
# importo los librer√≠as para el modelo
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import RidgeCV, LassoCV
from sklearn import metrics

### Modelado SOLO con place_name y property_type y sin stratify

In [34]:
# Selecciono las columnas que considero features para modelar 
X = df2.loc[:,['property_type','place_name']]
y = df2['price_usd_per_m2']

# Convierto a dummies las categ√≥ricas
X = pd.get_dummies(X,drop_first=True)

# Separo en train/test
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=33)

X.shape, y.shape, X_train.shape,X_test.shape, y_train.shape, y_test.shape

((20003, 63), (20003,), (15002, 63), (5001, 63), (15002,), (5001,))

In [35]:
#prueba con crossvalidation con Ridge
rcv = RidgeCV(alphas=(0.0001,0.001,0.01,0.1,1,10,100,1000,10000), cv=5)

rcv.fit(X_train,y_train)
print('intercept: ',rcv.intercept_,'coef: ', rcv.coef_,'alpha: ', rcv.alpha_)

y_pred_rcv = rcv.predict(X_test)

metrics.r2_score(y_test, y_pred_rcv)

intercept:  1311.3551707175504 coef:  [ 1128.43505322  -121.13888115  -395.14157268    73.89565583
  -853.59661565  -353.30652376   283.08006416   150.9749338
   106.69310189  8817.65079911  -341.59556335  -488.15900159
     0.           -97.27984236  -461.81612746  -273.44868512
  -247.40438128  -396.51370632  -812.63872487  -470.68681946
  -887.22598688   906.33016347  -519.96144943  -312.15575253
 -1242.47515745  -314.64429442  -137.10570157  -756.77408633
   135.06820473  2227.21753494   728.91772806   613.43994611
   481.80015286  -751.03160704  -217.0853174   -659.09567771
 -1106.69102445  -552.50903902  -496.92611061  -736.93387432
  3012.48438538   386.93465417  -163.63936113  -446.75356194
  6602.88180252  -683.17564245  -549.45476421  -398.32942574
  -203.60145697  -602.61483271  -154.17767942  -386.12996254
  -454.06228414  -835.69638636  -174.54333179    29.74105565
  -578.90789739  -412.93501795  -103.57696848  -412.35589477
  -859.27949191  -273.41771636  -320.408521  ] alpha:  10.0

0.2792206480472492

### MinMaxScaler

In [36]:
from sklearn.preprocessing import MinMaxScaler
numericals = ['surface_total_in_m2','surface_covered_in_m2']

Z = df2[numericals]

scaler = MinMaxScaler()
scaler.fit(Z)

std_numerical_data = scaler.transform(Z)
std_df = pd.DataFrame(std_numerical_data)
std_df.columns = [i + '_std' for i in numericals]
df2 = pd.concat([df2, std_df.set_index(df2.index)], axis=1)
df2

,property_type,place_name,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,rooms,tiene_jardin,tiene_cochera,tiene_pileta,tiene_parrilla,cuota,surface_total_in_m2_std,surface_covered_in_m2_std
0,PH,Mataderos,62000.0,55.0,40.0,1127.272727,2.0,0.0,0.0,0.0,0.0,0,0.000270,0.000200
2,apartment,Mataderos,72000.0,55.0,55.0,1309.090909,2.0,0.0,0.0,0.0,0.0,0,0.000270,0.000275
13,apartment,Palermo Soho,111700.0,50.0,30.0,2234.000000,1.0,0.0,0.0,1.0,0.0,0,0.000245,0.000150
14,apartment,Palermo Soho,147900.0,42.0,31.0,3521.428571,1.0,0.0,0.0,1.0,0.0,0,0.000205,0.000155
16,PH,Mataderos,239000.0,140.0,98.0,1707.142857,4.0,1.0,0.0,0.0,1.0,0,0.000695,0.000490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121113,apartment,Palermo,265000.0,100.0,88.0,2650.000000,3.0,1.0,1.0,1.0,1.0,0,0.000495,0.000440
121120,apartment,Palermo Soho,160000.0,45.0,40.0,3555.555556,2.0,1.0,1.0,1.0,1.0,0,0.000220,0.000200
121124,apartment,Capital Federal,16100.0,115.0,62.0,140.000000,3.0,1.0,1.0,0.0,0.0,0,0.000570,0.000310
121131,apartment,Recoleta,325000.0,113.0,113.0,2876.106195,4.0,0.0,0.0,0.0,0.0,0,0.000560,0.000565
121138,apartment,Saavedra,208000.0,69.0,60.0,3014.492754,2.0,1.0,0.0,1.0,1.0,0,0.000340,0.000300

In [37]:
df2['place_name'].value_counts()

Palermo            1658
Belgrano           1626
Caballito          1536
Recoleta           1036
Villa Crespo        918
                   ...
Villa Real           27
Palermo Viejo        26
Villa Soldati        12
Villa Riachuelo       4
Catalinas             1
Name: place_name, Length: 62, dtype: int64

In [38]:
# Eliminamos todos los barrios con menos de 250 entradas
group_place_name = df2.groupby('place_name')['place_name'].count()
lista_barrios = []

for x in group_place_name.index:
    if group_place_name[x]>250:
        lista_barrios.append(x)
# list = [x for x in group_place_name.index if group_place_name[x]>250]


df2 = df2[df2['place_name'].isin(lista_barrios)]

In [39]:
df2.columns

Index(['property_type', 'place_name', 'price_aprox_usd', 'surface_total_in_m2',
       'surface_covered_in_m2', 'price_usd_per_m2', 'rooms', 'tiene_jardin',
       'tiene_cochera', 'tiene_pileta', 'tiene_parrilla', 'cuota',
       'surface_total_in_m2_std', 'surface_covered_in_m2_std'],
      dtype='object')

In [40]:
# Selecciono las columnas que considero features para modelar 
X = df2.loc[:,['property_type','place_name','surface_total_in_m2','surface_covered_in_m2', 'rooms','tiene_cochera','tiene_pileta','tiene_parrilla','cuota', 'surface_total_in_m2_std', 'surface_covered_in_m2_std' ]]
y = df2['price_usd_per_m2']

# Convierto a dummies las categ√≥ricas
X = pd.get_dummies(X,drop_first=True)

# Separo en train/test
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=33, stratify = df2['place_name'])

X.shape, y.shape, X_train.shape,X_test.shape, y_train.shape, y_test.shape

((16128, 34), (16128,), (12096, 34), (4032, 34), (12096,), (4032,))

In [41]:
lr = LinearRegression()

lr.fit(X_train,y_train)
lr.intercept_, lr.coef_

(-41000353.43763647,
 array([ 4.10015885e+07, -6.99998239e-01, -5.31526778e+01,  1.65980395e+02,
         1.17969296e+03,  7.84163793e+01,  1.80093800e+03, -8.20027655e+12,
         3.54508584e-02,  8.53444648e+02, -4.10379236e+02, -4.98352954e+02,
        -2.20829925e+02,  4.74574498e+02,  1.04353886e+02,  6.81417806e+03,
        -4.35835572e+02, -4.16518126e+02, -5.14549935e+02, -6.62992760e+02,
        -1.35618707e+03, -2.14981676e+02,  5.46167273e+01,  3.21353554e+02,
         2.56459209e+03,  6.35762719e+02, -5.35211155e+02,  5.90028968e+03,
        -8.11829553e+02, -6.47105765e+01, -3.22538031e+02, -6.05440064e+01,
        -5.46157771e+02, -4.39828054e+02]))

In [42]:
y_pred = lr.predict(X_test)

metrics.r2_score(y_test, y_pred)

0.22990622411415607

## Ridge

In [43]:
#prueba con crossvalidation con Ridge
rcv = RidgeCV(alphas=(0.0001,0.001,0.01,0.1,1,10,100,1000,10000), cv=5)

rcv.fit(X_train,y_train)
rcv.intercept_, rcv.coef_, rcv.alpha_

(1355.7517569368374,
 array([ 6.42244151e-01, -6.49183233e-01, -5.59850033e+01,  1.72488136e+02,
         1.19425559e+03,  8.50862262e+01,  1.83377889e+03,  3.21126161e-06,
        -3.24592975e-06,  8.42700399e+02, -4.07372718e+02, -5.88796540e+02,
        -3.16769558e+02,  3.58946788e+02, -9.78177894e+00,  6.55470619e+03,
        -5.46317132e+02, -5.08346030e+02, -6.19920845e+02, -7.43086017e+02,
        -1.41028002e+03, -3.23156570e+02, -5.94760136e+01,  1.91146717e+02,
         2.36428505e+03,  5.22307710e+02, -6.27082208e+02,  5.62286468e+03,
        -9.10803784e+02, -1.74069553e+02, -4.15249231e+02, -1.65298825e+02,
        -6.55923558e+02, -5.33620073e+02]),
 10.0)

In [44]:
y_pred_rcv = rcv.predict(X_test)

metrics.r2_score(y_test, y_pred_rcv)

0.22995099219936244

## Lasso

In [45]:
#prueba con crossvalidation con Lasso
lcv = LassoCV(alphas=(0.0001,0.001,0.01,0.1,1,10,100,1000,10000), cv=5)

lcv.fit(X_train,y_train)
lcv.intercept_, lcv.coef_, lcv.alpha_

C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 30487438747.40732, tolerance: 16644940.533545844
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 58206733358.11859, tolerance: 16644940.533545844
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 56933965987.702644, tolerance: 16644940.533545844
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 56807098724.9186, tolerance: 16644940.533545844
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 56800313439.99651, tolerance: 16644940.533545844
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 56800484509.93904, tolerance: 16644940.533545844
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 56800547981.14218, tolerance: 16644940.533545844
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 38707328347.89493, tolerance: 19545329.30042956
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 70817333598.99916, tolerance: 19545329.30042956
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 69565323493.83017, tolerance: 19545329.30042956
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 69439569499.13402, tolerance: 19545329.30042956
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 69432878715.59203, tolerance: 19545329.30042956
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 69432953518.02925, tolerance: 19545329.30042956
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 69433078201.17433, tolerance: 19545329.30042956
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 45966670885.349625, tolerance: 18458053.233128473
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 68311273703.29922, tolerance: 18458053.233128473
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 66681384746.403275, tolerance: 18458053.233128473
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 66501892669.37471, tolerance: 18458053.233128473
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 66410086968.506905, tolerance: 18458053.233128473
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 66400438377.09901, tolerance: 18458053.233128473
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 66398781626.59824, tolerance: 18458053.233128473
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 66397545618.51787, tolerance: 18458053.233128473
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 40848306777.49385, tolerance: 19623767.59482889
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1197029127.544159, tolerance: 19623767.59482889
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 71641614472.45946, tolerance: 19623767.59482889
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 70530054767.4472, tolerance: 19623767.59482889
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 70421971056.42613, tolerance: 19623767.59482889
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 70417667288.86484, tolerance: 19623767.59482889
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 70418174087.93472, tolerance: 19623767.59482889
  positive,
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:644: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 70418328922.58047, tolerance: 19623767.59482889
  positive,

C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.068e+10, tolerance: 2.284e+07
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive

(1239.6738733947525,
 array([ 1.91316387e-01, -2.10276820e-01, -5.23059592e+01,  1.65960021e+02,
         1.17954937e+03,  7.94924408e+01,  1.80005369e+03,  4.21206143e+04,
        -3.97139300e+04,  8.50021164e+02, -4.07741960e+02, -5.00922485e+02,
        -2.21871822e+02,  4.72242632e+02,  1.02964941e+02,  6.81169311e+03,
        -4.37904017e+02, -4.18200527e+02, -5.17124849e+02, -6.64765680e+02,
        -1.35940650e+03, -2.16294733e+02,  5.23729267e+01,  3.19804602e+02,
         2.56269920e+03,  6.33570408e+02, -5.36840847e+02,  5.89716533e+03,
        -8.14034429e+02, -6.67034029e+01, -3.24598314e+02, -6.30419117e+01,
        -5.48340842e+02, -4.42291339e+02]),
 0.0001)

In [46]:
y_pred_lcv = lcv.predict(X_test)

metrics.r2_score(y_test, y_pred_lcv)

0.22992004253245335

## Portfolio de Departamentos

In [47]:
# Seleccionar mediante muestreo aleatorio simple una submuestra de 100 (cambiar la columna seleccionada por la columna 
# del modelo, utilic√© el precio aproximado en usd ya que posteriormente vamos a estimar un precio en funci√≥n del precio/m2 
# y la superficie)

portafolio = df2['price_aprox_usd'].sample(100)
portafolio

# Determinar capital inicial

cap_inicial = portafolio.sum()
print('Nuestro capital inicial es: ', cap_inicial)

df2['price_usd_per_m2_predic'] = df2.apply(lambda row: row['price_usd_per_m2']*0.8, axis=1)

# Determinar el error del precio de las propiedades 

# Se crea una columna con el precio de predicci√≥n
# (Cambiar los nombres de las columnas por los nombres de las columnas del modelo)
df2['price_aprox_usd_predic'] = df2.apply((lambda row: row['price_usd_per_m2_predic']*row['surface_covered_in_m2']), axis=1)

# Se crea una columna con la diferencia entre el precio real y el precio estimado por el modelos. 
# Se normaliza el error dividiendo por el precio real (cambiar los nombres de las variables)

df2['error_normalizado'] = df2.apply((lambda row: (row['price_aprox_usd_predic']-row['price_aprox_usd'])/row['price_aprox_usd']), axis=1)

# Se genera una m√°scara con los √≠ndice de las 100 propiedades que m√°s se alejan del valor predicho, con diferencia negativa
menor_error_mask= (df2['error_normalizado'].sort_values(ascending=False).head(100)).index


# Se calcula el capital que se necesitar√≠a para adquirir las 100 propiedades de menor valor. 
cap_menor = df2.loc[menor_error_mask,'price_aprox_usd'].sum()
print(cap_menor)

Nuestro capital inicial es:  24951343.0

C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

14115791.629999999

C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

# Gr√°ficos

In [48]:
# Apartir de "df2" con los ultimos destiles e imputaciones realizados sobre "df"
# y a partir tambien de un jointplot en "df" que perdi en el que a ojo selecciones las columnas relevantes; 2, 3, 4 y 5
df2

df3 = df2.iloc[:,[2,3,4,5]]
df3

# vemos entre cuales variables existe correlacion relevante.

sns.pairplot(df3);

NameError: name 'sns' is not defined

In [ ]:
# Tomando aquellas con mayor coeficiente de correlatividad : graficos particulares aislados.

# Precio por metro contra total de la Propiedad.
df4 = df3.loc[:,['price_usd_per_m2','price_aprox_usd']]
df4 = sns.FacetGrid(df3)
graf_1 = df4.map(sns.scatterplot, "price_usd_per_m2","price_aprox_usd")

In [ ]:
# m^2 totales contra precio total de la propiedad.
df5 = df3.loc[:,['surface_total_in_m2','price_aprox_usd']]
df5 = sns.FacetGrid(df3)
graf_2 = df5.map(sns.scatterplot, "surface_total_in_m2","price_aprox_usd")

In [ ]:
#superficie total contra precio de la propiedad.
df6 = df3.loc[:,['surface_covered_in_m2','price_aprox_usd']]
df6 = sns.FacetGrid(df3)
graf_3 = df6.map(sns.scatterplot, "surface_covered_in_m2","price_aprox_usd")