In [1]:
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
#import seaborn as sns
import re

In [2]:
location= 'Data/properatti.csv'

df = pd.read_csv(location, index_col=0)

In [3]:
# Filtro s√≥lo CABA y elmino los stores del tipo de propiedad
df2 = df[(df['property_type'].isin(['apartment','house','PH'])) & (df['state_name'] == 'Capital Federal')]

# Chequeo NaN
display(df2.info())

# Saco las columnas operatcion y estado, ya que son columnas con un solo valor y sin NA
df2 = df2.drop(['lat-lon','rooms','floor','expenses','operation', 'state_name', 'lat','lon','place_with_parent_names', 'country_name', 'geonames_id','price','currency'], axis=1)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30952 entries, 0 to 121219
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   operation                   30952 non-null  object
 1   property_type               30952 non-null  object
 2   place_name                  30952 non-null  object
 3   place_with_parent_names     30952 non-null  object
 4   country_name                30952 non-null  object
 5   state_name                  30952 non-null  object
 6   geonames_id                 29737 non-null  float64
 7   lat-lon                     22631 non-null  object
 8   lat                         22631 non-null  float64
 9   lon                         22631 non-null  float64
 10  price                       27828 non-null  float64
 11  currency                    27828 non-null  object
 12  price_aprox_local_currency  27828 non-null  float64
 13  price_aprox_usd             27828 non-null  float64
 14  surface_total_in_m2         25372 non-null  float64
 15  surface_covered_in_m2       28800 non-null  float64
 16  price_usd_per_m2            22519 non-null  float64
 17  price_per_m2                26276 non-null  float64
 18  floor                       3001 non-null   float64
 19  rooms                       15283 non-null  float64
 20  expenses                    6390 non-null   float64
 21  properati_url               30952 non-null  object
 22  description                 30952 non-null  object
 23  title                       30952 non-null  object
 24  image_thumbnail             30477 non-null  object
dtypes: float64(13), object(12)
memory usage: 6.1+ MB

None

In [4]:
df2['place_name'].value_counts()

Belgrano           2925
Palermo            2773
Caballito          2235
Villa Urquiza      1605
Recoleta           1453
                   ...
Palermo Viejo        36
Villa Real           36
Villa Soldati        13
Villa Riachuelo       6
Catalinas             3
Name: place_name, Length: 62, dtype: int64

In [5]:
df2.columns

Index(['property_type', 'place_name', 'price_aprox_local_currency',
       'price_aprox_usd', 'surface_total_in_m2', 'surface_covered_in_m2',
       'price_usd_per_m2', 'price_per_m2', 'properati_url', 'description',
       'title', 'image_thumbnail'],
      dtype='object')

## Features de "amenities"

In [6]:
def clasificarAmenities(dataset):
    ##esta funcion modifica el dataset de manera que agrega las columnas de amenities
    #inicializo columnas
    dataset['tiene_jardin'] = np.NaN
    dataset['tiene_cochera'] = np.NaN
    dataset['tiene_pileta'] = np.NaN
    dataset['tiene_parrilla'] = np.NaN
    
    ##regex
    #Expresiones regulares a utilizar
    re_jardin = re.compile("(jardin|garden|green|parque|parquizado|pasto)+|\s(sum)+", flags=re.IGNORECASE)
    re_cochera = re.compile("(garage|cochera)+|\s(sum)+", flags=re.IGNORECASE)
    re_pileta = re.compile("(pileta|piscina|pile)+|\s(sum)+", flags=re.IGNORECASE)
    re_parrilla = re.compile("(parrilla|bbq|barbaque|asado|asador)+|\s(sum)+", flags=re.IGNORECASE)
    
    #
    for i in dataset.description.index:
        
        dataset.tiene_jardin[i] = 0
        dataset.tiene_cochera[i] = 0
        dataset.tiene_pileta[i] = 0
        dataset.tiene_parrilla[i] = 0
        
        if dataset['description'][i] is not None:
            
            reg_search = re_jardin.search(str(dataset['description'][i]))
            if reg_search:
                dataset.tiene_jardin[i] = 1
                
            reg_search = re_cochera.search(str(dataset['description'][i]))
            if reg_search:
                dataset.tiene_cochera[i] = 1
                
            reg_search = re_pileta.search(str(dataset['description'][i]))
            if reg_search:
                dataset.tiene_pileta[i] = 1
                
            reg_search = re_parrilla.search(str(dataset['description'][i]))
            if reg_search:
                dataset.tiene_parrilla[i] = 1
                
                
        if dataset['title'][i] is not None:
            
            reg_search = re_jardin.search(str(dataset['title'][i]))
            if reg_search:
                dataset.tiene_jardin[i] = 1
                
            reg_search = re_cochera.search(str(dataset['title'][i]))
            if reg_search:
                dataset.tiene_cochera[i] = 1
                
            reg_search = re_pileta.search(str(dataset['title'][i]))
            if reg_search:
                dataset.tiene_pileta[i] = 1
                
            reg_search = re_parrilla.search(str(dataset['title'][i]))
            if reg_search:
                dataset.tiene_parrilla[i] = 1                
                
                              
        if dataset['properati_url'][i] is not None:
            
            reg_search = re_jardin.search(str(dataset['properati_url'][i]))
            if reg_search:
                dataset.tiene_jardin[i] = 1
                
            reg_search = re_cochera.search(str(dataset['properati_url'][i]))
            if reg_search:
                dataset.tiene_cochera[i] = 1
                
            reg_search = re_pileta.search(str(dataset['properati_url'][i]))
            if reg_search:
                dataset.tiene_pileta[i] = 1
                
            reg_search = re_parrilla.search(str(dataset['properati_url'][i]))
            if reg_search:
                dataset.tiene_parrilla[i] = 1                
                  
    return dataset

In [7]:
clasificarAmenities(df2)

C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\tomym\anaconda3\envs\seaborn\lib\site-packages\ipykernel_launcher.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,property_type,place_name,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,properati_url,description,title,image_thumbnail,tiene_jardin,tiene_cochera,tiene_pileta,tiene_parrilla
0,PH,Mataderos,1093959.00,62000.0,55.0,40.0,1127.272727,1550.000000,http://www.properati.com.ar/15bo8_venta_ph_mat...,"2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO,...",2 AMB TIPO CASA SIN EXPENSAS EN PB,https://thumbs4.properati.com/8/BluUYiHJLhgIIK...,0.0,0.0,0.0,0.0
2,apartment,Mataderos,1270404.00,72000.0,55.0,55.0,1309.090909,1309.090909,http://www.properati.com.ar/15bod_venta_depart...,2 AMBIENTES 3ER PISO LATERAL LIVING COMEDOR AM...,2 AMB 3ER PISO CON ASCENSOR APTO CREDITO,https://thumbs4.properati.com/5/SXKr34F_IwG3W_...,0.0,0.0,0.0,0.0
3,PH,Liniers,1676227.50,95000.0,NaN,NaN,NaN,NaN,http://www.properati.com.ar/15boh_venta_ph_lin...,PH 3 ambientes con patio. Hay 3 deptos en lote...,PH 3 amb. cfte. reciclado,https://thumbs4.properati.com/3/DgIfX-85Mog5SP...,0.0,0.0,0.0,0.0
7,apartment,Belgrano,2434941.00,138000.0,45.0,40.0,3066.666667,3450.000000,http://www.properati.com.ar/15bot_venta_depart...,EXCELENTE MONOAMBIENTE A ESTRENAR AMPLIO SUPER...,JOSE HERNANDEZ 1400 MONOAMBIENTE ESTRENAR CAT...,https://thumbs4.properati.com/1/IHxARynlr8sPEW...,0.0,0.0,1.0,0.0
8,apartment,Belgrano,3440677.50,195000.0,65.0,60.0,3000.000000,3250.000000,http://www.properati.com.ar/15bou_venta_depart...,EXCELENTE DOS AMBIENTES ESTRENAR AMPLIO SUPER...,"JOSE HERNANDEZ 1400 DOS AMBIENTES ESTRENAR ,...",https://thumbs4.properati.com/2/J3zOjgaFHrkvnv...,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121160,apartment,Belgrano,7234245.00,410000.0,157.0,NaN,2611.464968,NaN,http://www.properati.com.ar/1cj5v_venta_depart...,Edificio en esquina de muy buena categor√≠a de ...,Av .Luis Maria Campos 1400- Belgrano-Capital F...,https://thumbs4.properati.com/0/zeLNBuyylOJL7z...,1.0,0.0,0.0,0.0
121209,apartment,Belgrano,7234245.00,410000.0,157.0,NaN,2611.464968,NaN,http://www.properati.com.ar/1cj7c_venta_depart...,Edificio en esquina de muy buena categor√≠a de ...,Av .Luis Maria Campos 1400- Belgrano-Capital F...,https://thumbs4.properati.com/0/zeLNBuyylOJL7z...,1.0,0.0,0.0,0.0
121215,apartment,Belgrano,15350715.00,870000.0,113.0,93.0,7699.115044,9354.838710,http://www.properati.com.ar/1cja2_venta_depart...,TORRE FORUM ALCORTA - M√ÅXIMA CATEGOR√çA.Impecab...,Torre Forum Alcorta- Impecable 3 ambientes,https://thumbs4.properati.com/1/bjms0KnaAnlNoQ...,0.0,1.0,1.0,1.0
121217,apartment,Villa Urquiza,2320251.75,131500.0,46.0,39.0,2858.695652,3371.794872,http://www.properati.com.ar/1cja7_venta_depart...,VENTA DEPARTAMENTO AMBIENTE DIVISIBLE A ESTREN...,VENTA DEPARTAMENTO AMBIENTE DIVISIBLE A ESTREN...,https://thumbs4.properati.com/9/YAe_-2gRVykADP...,0.0,1.0,0.0,1.0
121219,apartment,Capital Federal,2276140.50,129000.0,77.0,77.0,1675.324675,1675.324675,http://www.properati.com.ar/1cjaa_venta_depart...,Departamento de 77 m2 apto profesional. Edific...,Departamento apto profesional en el Centro,https://thumbs4.properati.com/8/mNEsnQWqB7joBF...,0.0,0.0,0.0,0.0

## Columnas a agregar/eliminar

- Amenities: Booleano. Pileta, garage/cochera, parrilla, sum, garden/jardin
- Cuota: Booleano. Ver si sigue aplicando para planes, y si eliminamos o no.
- superficie: unificar los regex de los dos grupos
- Sup total y cubierta: Tomas buscar√° en los trabajos del resto. Julio hab√≠a imputado esto, traer el c√≥digo al nuevo dataset. Revisar le tema de las que tiene valores diferentes.
- image_thumbnail: Ver si los duplicados que se encontraron son relevantes en el nuevo dataset, y ulego eliminarla
- Floor: Aplicar el regex y ver con cuantos datos nos quedamos.
- rooms y ambientes: Ver los regex que se armaron, como aplican al nuevo dataset
- expensas por ahora se elimina
- Description y title: Se saca todos los datos y se elimina

## Agregado de columnas "ambiuentes", "cuota"e imputaci√≥n de superficie

In [8]:
def superficie(df2):

    #regex para encontrar las diferentes caracter√≠sticas

    patron = '(?P<m2>\d\d\d+\s\s*m2|\d\d\d+\s\s*M2|\d\d\d+\s\s*metro|\d\d\d+\s\s*METRO)|(?P<ambiente>\d+\sambiente|\d+\sAMBIENTE|\d+\sAMB|\d+\samb|\d+\sAMBS|\d+\sambs)|(?P<balcon>balcon|BALCON)|(?P<planta_alta>planta\salta|PLANTA\sALTA)|(?P<patio>patio|PATIO)|(?P<duplex>duplex|DUPLEX)|(?P<cuota>cuota|CUOTA)|(?P<amenities>parrilla|bbq|barbaque|asado|asador|cochera|pileta|piscina|pile|patio|terraza|solarium|pile|jardin|garden|green|parque|parquizado|pasto)+|\s(sum)+'
    patron_regex = re.compile(patron)
    patron_match = df2.description.apply(lambda x : patron_regex.search(str(x)))

    # Extrae los metros cuadrados de la descripci√≥n, luego extrae el n√∫mero (sin unidad) y posteriormente elimina aquellos menores que 3 para que no tome por error el n√∫mero 2 de la unidad de medida
    # Genera una serie m2

    m2 = patron_match.apply(lambda x: x if x is None else x.group('m2'))
    patron_num = '\d+'
    patron_num_regex = re.compile(patron_num)
    m2 = m2.apply(lambda x: x if x is None else patron_num_regex.findall(x))
    # Extrae solo el valor de la superficie, evitando considerar el 2 de "m2"
    m2 = m2.apply(lambda x: x if x is None else x[0])
    m2 = pd.to_numeric(m2)
    m2 = m2.apply(lambda x: x if x is None else (None if x<3 else x))

    # Extrae la cantidad de ambientes, de la descripci√≥n, luego extrae el n√∫mero (sin unidad) y posteriormente elimina aquellos menores que 3 para que no tome por error el n√∫mero 2 de la unidad de medida
    # Genera una serie ambientes

    ambientes = patron_match.apply(lambda x: x if x is None else x.group('ambiente'))
    ambientes = ambientes.apply(lambda x: x if x is None else x[0])
    ambientes = pd.to_numeric(ambientes)


    # Extrae la cantidad de ambientes, balc√≥n, patio, duplex, y planta alta y amenities de la descripci√≥n. Genera una serie booleana

    #balcon = patron_match.apply(lambda x: x if x is None else x.group('balcon'))
    #balcon = balcon.apply(lambda x: False if x is None else True)

    #patio = patron_match.apply(lambda x: x if x is None else x.group('patio'))
    #patio = patio.apply(lambda x: False if x is None else True)

    #duplex = patron_match.apply(lambda x: x if x is None else x.group('duplex'))
    #duplex = duplex.apply(lambda x: False if x is None else True)

    #planta_alta = patron_match.apply(lambda x: x if x is None else x.group('planta_alta'))
    #planta_alta = planta_alta.apply(lambda x: False if x is None else True)

    #amenities = patron_match.apply(lambda x: x if x is None else x.group('amenities'))
    #amenities = amenities.apply(lambda x: False if x is None else True)

    cuota = patron_match.apply(lambda x: x if x is None else x.group('cuota'))
    cuota = cuota.apply(lambda x: 0 if x is None else 1)
    
    df2['sup_m2_re'] = m2
    df2['ambientes'] = ambientes
    df2['cuota'] = cuota
    
    return df2

In [9]:
superficie(df2)

,property_type,place_name,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,properati_url,description,title,image_thumbnail,tiene_jardin,tiene_cochera,tiene_pileta,tiene_parrilla,sup_m2_re,ambientes,cuota
0,PH,Mataderos,1093959.00,62000.0,55.0,40.0,1127.272727,1550.000000,http://www.properati.com.ar/15bo8_venta_ph_mat...,"2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO,...",2 AMB TIPO CASA SIN EXPENSAS EN PB,https://thumbs4.properati.com/8/BluUYiHJLhgIIK...,0.0,0.0,0.0,0.0,NaN,2.0,0
2,apartment,Mataderos,1270404.00,72000.0,55.0,55.0,1309.090909,1309.090909,http://www.properati.com.ar/15bod_venta_depart...,2 AMBIENTES 3ER PISO LATERAL LIVING COMEDOR AM...,2 AMB 3ER PISO CON ASCENSOR APTO CREDITO,https://thumbs4.properati.com/5/SXKr34F_IwG3W_...,0.0,0.0,0.0,0.0,NaN,2.0,0
3,PH,Liniers,1676227.50,95000.0,NaN,NaN,NaN,NaN,http://www.properati.com.ar/15boh_venta_ph_lin...,PH 3 ambientes con patio. Hay 3 deptos en lote...,PH 3 amb. cfte. reciclado,https://thumbs4.properati.com/3/DgIfX-85Mog5SP...,0.0,0.0,0.0,0.0,NaN,3.0,0
7,apartment,Belgrano,2434941.00,138000.0,45.0,40.0,3066.666667,3450.000000,http://www.properati.com.ar/15bot_venta_depart...,EXCELENTE MONOAMBIENTE A ESTRENAR AMPLIO SUPER...,JOSE HERNANDEZ 1400 MONOAMBIENTE ESTRENAR CAT...,https://thumbs4.properati.com/1/IHxARynlr8sPEW...,0.0,0.0,1.0,0.0,NaN,NaN,0
8,apartment,Belgrano,3440677.50,195000.0,65.0,60.0,3000.000000,3250.000000,http://www.properati.com.ar/15bou_venta_depart...,EXCELENTE DOS AMBIENTES ESTRENAR AMPLIO SUPER...,"JOSE HERNANDEZ 1400 DOS AMBIENTES ESTRENAR ,...",https://thumbs4.properati.com/2/J3zOjgaFHrkvnv...,0.0,0.0,1.0,0.0,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121160,apartment,Belgrano,7234245.00,410000.0,157.0,NaN,2611.464968,NaN,http://www.properati.com.ar/1cj5v_venta_depart...,Edificio en esquina de muy buena categor√≠a de ...,Av .Luis Maria Campos 1400- Belgrano-Capital F...,https://thumbs4.properati.com/0/zeLNBuyylOJL7z...,1.0,0.0,0.0,0.0,NaN,NaN,0
121209,apartment,Belgrano,7234245.00,410000.0,157.0,NaN,2611.464968,NaN,http://www.properati.com.ar/1cj7c_venta_depart...,Edificio en esquina de muy buena categor√≠a de ...,Av .Luis Maria Campos 1400- Belgrano-Capital F...,https://thumbs4.properati.com/0/zeLNBuyylOJL7z...,1.0,0.0,0.0,0.0,NaN,NaN,0
121215,apartment,Belgrano,15350715.00,870000.0,113.0,93.0,7699.115044,9354.838710,http://www.properati.com.ar/1cja2_venta_depart...,TORRE FORUM ALCORTA - M√ÅXIMA CATEGOR√çA.Impecab...,Torre Forum Alcorta- Impecable 3 ambientes,https://thumbs4.properati.com/1/bjms0KnaAnlNoQ...,0.0,1.0,1.0,1.0,NaN,NaN,0
121217,apartment,Villa Urquiza,2320251.75,131500.0,46.0,39.0,2858.695652,3371.794872,http://www.properati.com.ar/1cja7_venta_depart...,VENTA DEPARTAMENTO AMBIENTE DIVISIBLE A ESTREN...,VENTA DEPARTAMENTO AMBIENTE DIVISIBLE A ESTREN...,https://thumbs4.properati.com/9/YAe_-2gRVykADP...,0.0,1.0,0.0,1.0,NaN,NaN,0
121219,apartment,Capital Federal,2276140.50,129000.0,77.0,77.0,1675.324675,1675.324675,http://www.properati.com.ar/1cjaa_venta_depart...,Departamento de 77 m2 apto profesional. Edific...,Departamento apto profesional en el Centro,https://thumbs4.properati.com/8/mNEsnQWqB7joBF...,0.0,0.0,0.0,0.0,NaN,NaN,0

In [10]:
mask_sup_cov = (df2['sup_m2_re'].notna()) & (df2['surface_covered_in_m2'].isna())
mask_sup_cov.sum()

82

In [11]:
# Funci√≥n que completa datos faltantes de superficie con datos extra√≠dos de la descripci√≥n.
def compl_m2_re (row):
    if row['surface_covered_in_m2']>=0:
        result = row['surface_covered_in_m2']
    else:
        result = row['sup_m2_re']
    return result

df2['surface_covered_in_m2'] = df2.apply(compl_m2_re, axis = 1)

In [12]:
# Verifico si se imputaron correctamente.

df2['surface_covered_in_m2'].notnull().sum()

28882

In [13]:
# Determinar la cantidad de filas que pueden tener invertidas los datos de superficie cubierta con superficie total

sup_mask = df2['surface_covered_in_m2'] > df2['surface_total_in_m2']
print(f'Cantidad de filas con sup_cov > sup_total {sup_mask.sum()}')

Cantidad de filas con sup_cov > sup_total 131

In [14]:
# Funci√≥n para corregir los valores invertidos de superficie cubierta y superficie total

df2['surface_covered_in_m2_aux'] = df2['surface_covered_in_m2']

def invertir_sup_cov (row):
    if (row['surface_covered_in_m2'] > row['surface_total_in_m2']):
        return row['surface_total_in_m2']
    else:
        return row['surface_covered_in_m2']

def invertir_sup_tot (row):
    if (row['surface_covered_in_m2'] == row['surface_total_in_m2']):
        return row['surface_covered_in_m2_aux']
    else:
        return row['surface_total_in_m2'] 
    
df2.loc[sup_mask,'surface_covered_in_m2'] = df2.apply(invertir_sup_tot, axis=1)
df2.loc[sup_mask,'surface_total_in_m2']  = df2.apply(invertir_sup_tot, axis=1)

In [15]:
df2.columns

Index(['property_type', 'place_name', 'price_aprox_local_currency',
       'price_aprox_usd', 'surface_total_in_m2', 'surface_covered_in_m2',
       'price_usd_per_m2', 'price_per_m2', 'properati_url', 'description',
       'title', 'image_thumbnail', 'tiene_jardin', 'tiene_cochera',
       'tiene_pileta', 'tiene_parrilla', 'sup_m2_re', 'ambientes', 'cuota',
       'surface_covered_in_m2_aux'],
      dtype='object')

In [16]:
# Elimino la columna auxiliar generada

df2.drop('surface_covered_in_m2_aux', axis=1, inplace=True)
df2.drop('sup_m2_re', axis=1, inplace=True)
#df2.drop('ambientes', axis=1, inplace=True)

In [17]:
# Verificaci√≥n de la correcci√≥n de cambio de columnas e imputaci√≥n.

sup_mask = df2['surface_covered_in_m2'] > df2['surface_total_in_m2']
print(f'Cantidad de filas con sup_cov > sup_total {sup_mask.sum()}')
display(df2.info())

Cantidad de filas con sup_cov > sup_total 0
<class 'pandas.core.frame.DataFrame'>
Int64Index: 30952 entries, 0 to 121219
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_type               30952 non-null  object
 1   place_name                  30952 non-null  object
 2   price_aprox_local_currency  27828 non-null  float64
 3   price_aprox_usd             27828 non-null  float64
 4   surface_total_in_m2         25372 non-null  float64
 5   surface_covered_in_m2       28882 non-null  float64
 6   price_usd_per_m2            22519 non-null  float64
 7   price_per_m2                26276 non-null  float64
 8   properati_url               30952 non-null  object
 9   description                 30952 non-null  object
 10  title                       30952 non-null  object
 11  image_thumbnail             30477 non-null  object
 12  tiene_jardin                30952 non-null  float64
 13  tiene_cochera               30952 non-null  float64
 14  tiene_pileta                30952 non-null  float64
 15  tiene_parrilla              30952 non-null  float64
 16  ambientes                   13027 non-null  float64
 17  cuota                       30952 non-null  int64
dtypes: float64(11), int64(1), object(6)
memory usage: 5.5+ MB

None

##

In [18]:
# sns.jointplot(x='surface_covered_in_m2', y='surface_total_in_m2',data=df2, hue='property_type',xlim=(0,500), ylim=(0,500))

In [19]:
display(df2.columns)
df2.head()

Index(['property_type', 'place_name', 'price_aprox_local_currency',
       'price_aprox_usd', 'surface_total_in_m2', 'surface_covered_in_m2',
       'price_usd_per_m2', 'price_per_m2', 'properati_url', 'description',
       'title', 'image_thumbnail', 'tiene_jardin', 'tiene_cochera',
       'tiene_pileta', 'tiene_parrilla', 'ambientes', 'cuota'],
      dtype='object')

,property_type,place_name,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,properati_url,description,title,image_thumbnail,tiene_jardin,tiene_cochera,tiene_pileta,tiene_parrilla,ambientes,cuota
0,PH,Mataderos,1093959.0,62000.0,55.0,40.0,1127.272727,1550.000000,http://www.properati.com.ar/15bo8_venta_ph_mat...,"2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO,...",2 AMB TIPO CASA SIN EXPENSAS EN PB,https://thumbs4.properati.com/8/BluUYiHJLhgIIK...,0.0,0.0,0.0,0.0,2.0,0
2,apartment,Mataderos,1270404.0,72000.0,55.0,55.0,1309.090909,1309.090909,http://www.properati.com.ar/15bod_venta_depart...,2 AMBIENTES 3ER PISO LATERAL LIVING COMEDOR AM...,2 AMB 3ER PISO CON ASCENSOR APTO CREDITO,https://thumbs4.properati.com/5/SXKr34F_IwG3W_...,0.0,0.0,0.0,0.0,2.0,0
3,PH,Liniers,1676227.5,95000.0,NaN,NaN,NaN,NaN,http://www.properati.com.ar/15boh_venta_ph_lin...,PH 3 ambientes con patio. Hay 3 deptos en lote...,PH 3 amb. cfte. reciclado,https://thumbs4.properati.com/3/DgIfX-85Mog5SP...,0.0,0.0,0.0,0.0,3.0,0
7,apartment,Belgrano,2434941.0,138000.0,45.0,40.0,3066.666667,3450.000000,http://www.properati.com.ar/15bot_venta_depart...,EXCELENTE MONOAMBIENTE A ESTRENAR AMPLIO SUPER...,JOSE HERNANDEZ 1400 MONOAMBIENTE ESTRENAR CAT...,https://thumbs4.properati.com/1/IHxARynlr8sPEW...,0.0,0.0,1.0,0.0,NaN,0
8,apartment,Belgrano,3440677.5,195000.0,65.0,60.0,3000.000000,3250.000000,http://www.properati.com.ar/15bou_venta_depart...,EXCELENTE DOS AMBIENTES ESTRENAR AMPLIO SUPER...,"JOSE HERNANDEZ 1400 DOS AMBIENTES ESTRENAR ,...",https://thumbs4.properati.com/2/J3zOjgaFHrkvnv...,0.0,0.0,1.0,0.0,NaN,0

In [20]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30952 entries, 0 to 121219
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_type               30952 non-null  object
 1   place_name                  30952 non-null  object
 2   price_aprox_local_currency  27828 non-null  float64
 3   price_aprox_usd             27828 non-null  float64
 4   surface_total_in_m2         25372 non-null  float64
 5   surface_covered_in_m2       28882 non-null  float64
 6   price_usd_per_m2            22519 non-null  float64
 7   price_per_m2                26276 non-null  float64
 8   properati_url               30952 non-null  object
 9   description                 30952 non-null  object
 10  title                       30952 non-null  object
 11  image_thumbnail             30477 non-null  object
 12  tiene_jardin                30952 non-null  float64
 13  tiene_cochera               30952 non-null  float64
 14  tiene_pileta                30952 non-null  float64
 15  tiene_parrilla              30952 non-null  float64
 16  ambientes                   13027 non-null  float64
 17  cuota                       30952 non-null  int64
dtypes: float64(11), int64(1), object(6)
memory usage: 5.5+ MB

## Conversion de pasos a dolares

Tipo de cambio promedio entre entre 'price_aprox_local_currency' y 'price_aprox_usd':  17.64 $/USD

In [21]:
def estimar_tipo_de_cambio(data):
    #'Esta funci√≥n estima el tipo de cambio promedio entre 'price_aprox_local_currency' y 'price_aprox_usd'
    mask_tipo_de_cambio = (data['price_aprox_local_currency'].notnull() & data['price_aprox_usd'].notnull())
    calculo_tipo_de_cambio = data.loc[mask_tipo_de_cambio, 'price_aprox_local_currency'] / data.loc[mask_tipo_de_cambio, 'price_aprox_usd']
    tipo_de_cambio = calculo_tipo_de_cambio.mean()
    valor = round(tipo_de_cambio, 2)
    return valor

In [22]:
valor_dolar = estimar_tipo_de_cambio(df2)
print(valor_dolar)

17.64

In [23]:
def calculo_valor_total_pesos_dolar(dataframe, valor_dolar):
    #precio m2 en pesos a precio m2 en dolares
    for i in dataframe.index:
        if pd.isna(dataframe.loc[i, 'price_usd_per_m2']):
            dataframe.loc[i, 'price_usd_per_m2'] = dataframe.loc[i, 'price_per_m2'] / valor_dolar
    
    return dataframe

In [24]:
df2 = calculo_valor_total_pesos_dolar(df2, valor_dolar)

In [25]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30952 entries, 0 to 121219
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_type               30952 non-null  object
 1   place_name                  30952 non-null  object
 2   price_aprox_local_currency  27828 non-null  float64
 3   price_aprox_usd             27828 non-null  float64
 4   surface_total_in_m2         25372 non-null  float64
 5   surface_covered_in_m2       28882 non-null  float64
 6   price_usd_per_m2            27307 non-null  float64
 7   price_per_m2                26276 non-null  float64
 8   properati_url               30952 non-null  object
 9   description                 30952 non-null  object
 10  title                       30952 non-null  object
 11  image_thumbnail             30477 non-null  object
 12  tiene_jardin                30952 non-null  float64
 13  tiene_cochera               30952 non-null  float64
 14  tiene_pileta                30952 non-null  float64
 15  tiene_parrilla              30952 non-null  float64
 16  ambientes                   13027 non-null  float64
 17  cuota                       30952 non-null  int64
dtypes: float64(11), int64(1), object(6)
memory usage: 5.5+ MB

In [26]:
#Dropeo todas las features que necesitan tratamiento previo para servir
df2 = df2.drop(['description','title','image_thumbnail','price_per_m2','properati_url', 'price_aprox_local_currency'], axis=1)

In [27]:
df2 = df2.drop('ambientes',axis=1)

In [28]:
df2 = df2.dropna()

In [29]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21521 entries, 0 to 121219
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   property_type          21521 non-null  object
 1   place_name             21521 non-null  object
 2   price_aprox_usd        21521 non-null  float64
 3   surface_total_in_m2    21521 non-null  float64
 4   surface_covered_in_m2  21521 non-null  float64
 5   price_usd_per_m2       21521 non-null  float64
 6   tiene_jardin           21521 non-null  float64
 7   tiene_cochera          21521 non-null  float64
 8   tiene_pileta           21521 non-null  float64
 9   tiene_parrilla         21521 non-null  float64
 10  cuota                  21521 non-null  int64
dtypes: float64(8), int64(1), object(2)
memory usage: 2.0+ MB

## test modelado b√°sico

In [30]:
# importo los librer√≠as para el modelo
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import RidgeCV, LassoCV
from sklearn import metrics

In [31]:
df2['place_name'].value_counts()

Belgrano           1987
Palermo            1799
Caballito          1624
Recoleta           1093
Villa Urquiza      1052
                   ...
Agronom√≠a            23
Parque Chas          12
Villa Soldati         5
Villa Riachuelo       3
Catalinas             1
Name: place_name, Length: 62, dtype: int64

In [32]:
# Eliminamos todos los barrios con menos de 250 entradas
group_place_name = df2.groupby('place_name')['place_name'].count()
lista_barrios = []

for x in group_place_name.index:
    if group_place_name[x]>250:
        lista_barrios.append(x)
# list = [x for x in group_place_name.index if group_place_name[x]>250]


df2 = df2[df2['place_name'].isin(lista_barrios)]

In [33]:
df2.columns

Index(['property_type', 'place_name', 'price_aprox_usd', 'surface_total_in_m2',
       'surface_covered_in_m2', 'price_usd_per_m2', 'tiene_jardin',
       'tiene_cochera', 'tiene_pileta', 'tiene_parrilla', 'cuota'],
      dtype='object')

In [34]:
# Selecciono las columnas que considero features para modelar 
X = df2.loc[:,['property_type','place_name','surface_total_in_m2','surface_covered_in_m2','tiene_cochera','tiene_pileta','tiene_parrilla','cuota' ]]
y = df2['price_usd_per_m2']

# Convierto a dummies las categ√≥ricas
X = pd.get_dummies(X,drop_first=True)

# Separo en train/test
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=33, stratify = df2['place_name'])

X.shape, y.shape, X_train.shape,X_test.shape, y_train.shape, y_test.shape

((17766, 31), (17766,), (13324, 31), (4442, 31), (13324,), (4442,))

In [35]:
lr = LinearRegression()

lr.fit(X_train,y_train)
lr.intercept_, lr.coef_

(1664.9119397830723,
 array([-1.20426758e+00,  1.34541490e+00,  3.51422218e+02,  1.02847667e+03,
        -2.24925545e+01,  1.66130152e+03,  8.58615815e+02, -2.82362007e+02,
        -6.40254145e+02, -7.99824115e+02,  1.70642407e+02,  2.09557393e+01,
         6.25564438e+03, -5.42144407e+02, -6.93118436e+02, -9.31329702e+02,
        -6.83981536e+02, -1.02701692e+03,  6.27819632e+01,  3.26262222e+02,
        -2.50688305e+02, -1.25405138e+01,  2.44675687e+03,  4.67860822e+02,
        -5.56622724e+02,  6.80638143e+03, -7.38288641e+02, -3.40292285e+02,
        -3.81871185e+02, -5.70844230e+02, -7.52716984e+02]))

In [36]:
y_pred = lr.predict(X_test)

metrics.r2_score(y_test, y_pred)

0.2598557578168189

## Ridge

In [37]:
#prueba con crossvalidation con Ridge
rcv = RidgeCV(alphas=(0.0001,0.001,0.01,0.1,1,10,100,1000,10000), cv=5)

rcv.fit(X_train,y_train)
rcv.intercept_, rcv.coef_, rcv.alpha_

(1677.1714797956224,
 array([-1.20700499e+00,  1.34788658e+00,  3.51950969e+02,  1.02982685e+03,
        -2.15335320e+01,  1.66502690e+03,  8.57802832e+02, -2.83081231e+02,
        -6.49991844e+02, -8.08921739e+02,  1.58213360e+02,  8.19182770e+00,
         6.22946783e+03, -5.54303793e+02, -7.04069891e+02, -9.42668114e+02,
        -6.92545437e+02, -1.03463437e+03,  4.97923174e+01,  3.13461187e+02,
        -2.63326215e+02, -2.55086849e+01,  2.42596659e+03,  4.55344466e+02,
        -5.67716409e+02,  6.77106822e+03, -7.49890442e+02, -3.52098228e+02,
        -3.92147175e+02, -5.82951603e+02, -7.62208552e+02]),
 1.0)

In [38]:
y_pred_rcv = rcv.predict(X_test)

metrics.r2_score(y_test, y_pred_rcv)

0.2597433991234199

## Lasso

In [39]:
#prueba con crossvalidation con Lasso
lcv = LassoCV(alphas=(0.0001,0.001,0.01,0.1,1,10,100,1000,10000), cv=5)

lcv.fit(X_train,y_train)
lcv.intercept_, lcv.coef_, lcv.alpha_

(1650.6226977059591,
 array([-1.20777197e+00,  1.35071941e+00,  3.51387170e+02,  1.02734221e+03,
        -2.14218158e+01,  1.66090129e+03,  8.59742764e+02, -2.80653596e+02,
        -6.22912617e+02, -7.81206334e+02,  1.81499323e+02,  3.31816027e+01,
         6.26673523e+03, -5.27962153e+02, -6.77049163e+02, -9.16321398e+02,
        -6.64334150e+02, -1.00726561e+03,  7.21544186e+01,  3.38401485e+02,
        -2.33185612e+02,  0.00000000e+00,  2.45591986e+03,  4.79252709e+02,
        -5.39001083e+02,  6.81545523e+03, -7.23248885e+02, -3.25302827e+02,
        -3.61921979e+02, -5.56105171e+02, -7.33981817e+02]),
 0.1)

In [40]:
y_pred_lcv = lcv.predict(X_test)

metrics.r2_score(y_test, y_pred_lcv)

0.25987111144420494